name: DEPLOY

on:
  push:
    paths:
      - 'example-website/**'
      - '.github/workflows/deploy.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  deploy-web:
    name: Deploy EK Web Framework Example Website
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Install
      working-directory: example-website
      run: npm install
    
    - name: Build
      working-directory: example-website
      run: npx ng build --base-href=/ek-web-framework/
        
    - name: NoJekyll
      working-directory: example-website
      run: touch dist/example-website/browser/.nojekyll
    
    - name: Setup Pages
      uses: actions/configure-pages@v5
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: example-website/dist/example-website/browser

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
